cheetah:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  LF_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_JOINT1
    pid: {p: 20.0, i: 0.01, d: 1.0}
  LF_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_JOINT2
    pid: {p: 20.0, i: 0.01, d: 1.0}
  LF_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: LF_JOINT3
    pid: {p: 20.0, i: 0.01, d: 1.0}
  LB_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: LB_JOINT1
    pid: {p: 10.0, i: 0.01, d: 1.0}
  LB_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: LB_JOINT2
    pid: {p: 10.0, i: 0.01, d: 1.0}
  LB_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: LB_JOINT3
    pid: {p: 10.0, i: 0.01, d: 1.0}

  RF_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_JOINT1
    pid: {p: 10.0, i: 0.01, d: 1.0}
  RF_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_JOINT2
    pid: {p: 10.0, i: 0.01, d: 1.0}
  RF_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: RF_JOINT3
    pid: {p: 10.0, i: 0.01, d: 1.0}
  RB_joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: RB_JOINT1
    pid: {p: 10.0, i: 0.01, d: 1.0}
  RB_joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: RB_JOINT2
    pid: {p: 10.0, i: 0.01, d: 1.0}
  RB_joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: RB_JOINT3
    pid: {p: 10.0, i: 0.01, d: 1.0}
